name: bloc_structure_setup
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  avatars: ^3.0.2
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  dio: ^5.8.0+1
  talker_dio_logger: ^4.9.0
  skeletonizer: ^2.0.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  go_router: ^15.2.0
  dartz: ^0.10.1
  infinite_scroll_pagination: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner: any

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splash_logo.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

